name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server-tests:

    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ${{env.working-directory}}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ${{env.working-directory}}
    - name: Generate key
      run: php artisan key:generate
      working-directory: ${{env.working-directory}}
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ${{env.working-directory}}
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ${{env.working-directory}}
#    - name: Execute tests (Unit and Feature tests) via PHPUnit
#      env:
#        DB_CONNECTION: sqlite
#        DB_DATABASE: server/database/database.sqlite
#      run: server/vendor/bin/phpunit
#      working-directory: ${{env.working-directory}}
#    - name: Server
#      run: php artisan serve
#      working-directory: ${{env.working-directory}}
